const types = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  REGISTER_USER: 'REGISTER_USER',
  MODIFY_USER: 'MODIFY_USER',
  CHEER_SCORE: 'CHEER_SCORE',
  CHEER_SCORE2: 'CHEER_SCORE2',
  SET_BAR_POSITION: 'SET_BAR_POSITION',
  GET_VIEWPOINTS: 'GET_VIEWPOINTS',
  IS_ADMIN: 'IS_ADMIN',
  GET_NUM_OF_EACH_TEAM: 'GET_NUM_OF_EACH_TEAM',
  INIT_VIEWPOINT: 'INIT_VIEWPOINT',
};

export default types;
