const types = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  REGISTER_USER: 'REGISTER_USER',
  MODIFY_USER: 'MODIFY_USER',
  CHOOSE_EMOGEE: 'CHOOSE_EMOGEE',
  CHEER_SCORE: 'CHEER_SCORE',
  CHEER_SCORE2: 'CHEER_SCORE2',
  SET_BAR_POSITION: 'SET_BAR_POSITION',
};

export default types;
